version: "2"

run:
  go: "1.22"
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - godox
    - goheader
    - gomoddirectives
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - maintidx
    - makezero
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
