package formats

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"strconv"
	"strings"
	"time"

	"subgo/subtitle"
)

// assFormat implements the ASS/SSA subtitle format.
type assFormat struct{}

func (assFormat) Name() string { return "ass" }

func (assFormat) Extensions() []string { return []string{".ass", ".ssa"} }

func (assFormat) Decode(r io.Reader) (subtitle.Subtitle, error) {
	scanner := bufio.NewScanner(r)
	var events []subtitle.Event

	// Track which section we're in
	inEvents := false
	var formatFields []string

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, ";") {
			continue
		}

		// Check for section headers
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section := strings.ToLower(line[1 : len(line)-1])
			inEvents = (section == "events")
			continue
		}

		if !inEvents {
			continue
		}

		// Parse Format line to know field order
		if strings.HasPrefix(line, "Format:") {
			formatStr := strings.TrimPrefix(line, "Format:")
			formatFields = parseASSFields(formatStr)
			continue
		}

		// Parse Dialogue lines
		if strings.HasPrefix(line, "Dialogue:") {
			dialogueStr := strings.TrimPrefix(line, "Dialogue:")
			event, err := parseASSDialogue(dialogueStr, formatFields)
			if err != nil {
				// Skip malformed lines instead of failing
				continue
			}
			events = append(events, event)
		}
	}

	if err := scanner.Err(); err != nil {
		return subtitle.Subtitle{}, err
	}

	return subtitle.Subtitle{Events: events}, nil
}

func (assFormat) Encode(w io.Writer, s subtitle.Subtitle) error {
	buf := &bytes.Buffer{}

	// Write script info section
	buf.WriteString("[Script Info]\n")
	buf.WriteString("; Script generated by subgo\n")
	buf.WriteString("ScriptType: v4.00+\n")
	buf.WriteString("PlayResX: 384\n")
	buf.WriteString("PlayResY: 288\n")
	buf.WriteString("\n")

	// Write default style
	buf.WriteString("[V4+ Styles]\n")
	buf.WriteString("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
	buf.WriteString("Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n")
	buf.WriteString("\n")

	// Write events
	buf.WriteString("[Events]\n")
	buf.WriteString("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")

	for _, e := range s.Events {
		// Convert newlines to \N for ASS format
		text := strings.ReplaceAll(e.Text, "\n", "\\N")
		fmt.Fprintf(buf, "Dialogue: 0,%s,%s,Default,,0,0,0,,%s\n",
			formatASSTimestamp(e.Start),
			formatASSTimestamp(e.End),
			text,
		)
	}

	_, err := w.Write(buf.Bytes())
	return err
}

// parseASSFields parses the Format line fields
func parseASSFields(s string) []string {
	parts := strings.Split(s, ",")
	fields := make([]string, len(parts))
	for i, p := range parts {
		fields[i] = strings.ToLower(strings.TrimSpace(p))
	}
	return fields
}

// parseASSDialogue parses a Dialogue line using the format fields
func parseASSDialogue(s string, formatFields []string) (subtitle.Event, error) {
	// ASS dialogue has comma-separated fields, but the last field (Text) can contain commas
	// So we split by comma but limit to len(formatFields) parts
	parts := strings.SplitN(s, ",", len(formatFields))
	if len(parts) < len(formatFields) {
		return subtitle.Event{}, fmt.Errorf("not enough fields in dialogue line")
	}

	// Build a map of field name -> value
	fieldMap := make(map[string]string)
	for i, field := range formatFields {
		if i < len(parts) {
			fieldMap[field] = strings.TrimSpace(parts[i])
		}
	}

	// Parse start time
	startStr, ok := fieldMap["start"]
	if !ok {
		return subtitle.Event{}, fmt.Errorf("missing Start field")
	}
	start, err := parseASSTimestamp(startStr)
	if err != nil {
		return subtitle.Event{}, err
	}

	// Parse end time
	endStr, ok := fieldMap["end"]
	if !ok {
		return subtitle.Event{}, fmt.Errorf("missing End field")
	}
	end, err := parseASSTimestamp(endStr)
	if err != nil {
		return subtitle.Event{}, err
	}

	// Get text
	text := fieldMap["text"]
	// Convert \N and \n to actual newlines
	text = strings.ReplaceAll(text, "\\N", "\n")
	text = strings.ReplaceAll(text, "\\n", "\n")

	return subtitle.Event{
		Start: start,
		End:   end,
		Text:  text,
	}, nil
}

// parseASSTimestamp parses ASS timestamp format: H:MM:SS.cc (centiseconds)
func parseASSTimestamp(s string) (time.Duration, error) {
	s = strings.TrimSpace(s)

	// Split by dot for centiseconds
	parts := strings.Split(s, ".")
	if len(parts) != 2 {
		return 0, fmt.Errorf("invalid ASS timestamp: %q", s)
	}

	timePart := parts[0]
	csPart := parts[1]

	// Parse time part H:MM:SS
	timeFields := strings.Split(timePart, ":")
	if len(timeFields) != 3 {
		return 0, fmt.Errorf("invalid ASS timestamp: %q", s)
	}

	h, err := strconv.Atoi(timeFields[0])
	if err != nil {
		return 0, err
	}
	m, err := strconv.Atoi(timeFields[1])
	if err != nil {
		return 0, err
	}
	sec, err := strconv.Atoi(timeFields[2])
	if err != nil {
		return 0, err
	}
	cs, err := strconv.Atoi(csPart)
	if err != nil {
		return 0, err
	}

	d := time.Hour*time.Duration(h) +
		time.Minute*time.Duration(m) +
		time.Second*time.Duration(sec) +
		time.Millisecond*time.Duration(cs*10) // centiseconds to milliseconds

	return d, nil
}

// formatASSTimestamp formats a duration as ASS timestamp: H:MM:SS.cc
func formatASSTimestamp(d time.Duration) string {
	if d < 0 {
		d = 0
	}
	h := int(d / time.Hour)
	d -= time.Duration(h) * time.Hour
	m := int(d / time.Minute)
	d -= time.Duration(m) * time.Minute
	sec := int(d / time.Second)
	d -= time.Duration(sec) * time.Second
	cs := int(d/time.Millisecond) / 10 // milliseconds to centiseconds

	return fmt.Sprintf("%d:%02d:%02d.%02d", h, m, sec, cs)
}
